### ISSUE TITLE
Loot level

### ISSUE THREAD

**Issue by Zuljita** [Syndaryl/DFRPGRandomDungeonGenerator#43]
Every campaign is different in terms of loot levels, Let's try to make an option to adjust how generous the generated loot is.

**Comment by Syndaryl** [comment]
Suggestion: A text box to type a factor to multiply treasure value in, and a ticky-box to request that instead of straight multiplication, the factor is passed into a function along with the difficulty of the encounter to produce a multiplier that gets bigger with the difficulty of the encounter?

**Comment by Syndaryl** [comment]
Although I point out that the treasure multipliers are defined in threatDistribution.js

**Comment by Syndaryl** [comment]
**Suggestion:**
STV = Standard treasure value, produced from the CER article
TS = treasure scale, entered by the user
N = party CER / encounter CER

Linear function:
Treasure = STV * TS

Exponential function:
Treasure = STV * (TS^(1/N))     - ak Treasure Scale to the power of one over N

All the below examples assume party CER of 225
Example, encounter CER 50, STV = $125, TS = 1.3, linear treasure = $162.5, exponential treasure = $132.50

Example, encounter CER 50, STV = $125, TS = 3, linear treasure = $375, exponential treasure = $159.56

Example, encounter CER 500, STV = $12,500, TS = 1.3, linear treasure = $16,250, exponential treasure = $22,393.27
Example, encounter CER 500, STV = $12,500, TS = 3, linear treasure = $37,500, exponential treasure = $143,608.28

I would use the exponential version with a TS in the range of 1.2 to 1.5 for my own campaigns I think.

**Comment by Zuljita** [comment]
I like that exponential option.  Makes real boss fights seem much more rewarding.

**Comment by Syndaryl** [comment]
The other thing that's important is being able to divorce treasure value from the party's CER, even if you generated the **dungeon** based on the party's CER. Being able to set the "benchmark" party CER at e.g. 200 so that any encounter of a given CER will have the same treasure throughout your campaign.
A GM who wants the dungeon _difficulty_ set independently of the Party's CER can put whatever number they want into the party CER box, but that ends up changing the bellcurve on treasure.

There's a passionate debate about encounter difficulty relative to character/party "level" (and indirectly, treasure awarded) amongst Elder Scrolls modders, as well as among GURPS players and I'm sure in the larger gaming community (whether CRPG or TRPG).
Skyrim's default state is that many encounters are scaled relative to your character's level: a wild animal encounter might be one wolf when you're level one, three wolves when you're level 5, a cave bear or a pack of frost wolves when you're level 10, etc. There are people who hate this, and change various encounters to fixed difficulties. Similarly, treasure is distributed based on the level of the encounter. There are also people who hate _that_ and make some or all the treasure distribution "flat" - removing the chance of animals to have eaten a ring or gem or some coins at high level, and making all treasure chests contain totally random loot, for example.

I think its important to accommodate both positions.

**Comment by Syndaryl** [comment]
I'm going to call this fixed. We do have a linear way of increasing treasure at the moment, which is under the control of the user . We also modify treasure based on distance.

Completely divorcing treasure from CER (or having some treasures divorced from CER) should be a separate issue.
